# _config.yml
# This file contains the primary configuration for your Jekyll site.

# Site settings
# The title of your website, displayed in the browser tab and site header.
title: Alaska INBRE Data Sciece Core Workshop

# Your email address (optional, for contact or RSS feed).
email: dmdrownX@alaska.edu

# A brief description of your site. This is often used in meta tags for SEO.
description: >-
  Dive into the world of genomics with cutting-edge nanopore sequencing technology! This 5-day workshop equips students and early-career researchers with essential data science skills for analyzing and interpreting genomic data. Learn to analyze and visualize your data using common computational tools.


# The base URL for your site.
# - For a User/Organization site (e.g., username.github.io), leave this as "".
# - For a Project site (e.g., username.github.io/repo-name), set this to "/repo-name".
baseurl: "dsc_workshop_2025"

# The full URL of your site. You can leave this blank for now, or set it to
# your GitHub Pages URL once you know it (e.g., https://yourusername.github.io).
url: ""

# Build settings
# Specifies the Markdown processor Jekyll will use. kramdown is a common choice.
markdown: kramdown

# The Jekyll theme to use. 'minima' is the default and a good starting point.
# AFTER
remote_theme: just-the-docs/just-the-docs@v0.10.1   # use the latest tag

# Optional—but recommended—site settings
title: "Nanopore Sequencing Workshop"
logo: "/assets/images/DSC_Wrokshop_2025_goofy.jpg"
color_scheme: light
search_enabled: true


# Plugins Jekyll will use. jekyll-feed generates an RSS feed for your blog posts.
plugins:
  - jekyll-feed

# Exclude files/folders from the Jekyll build process (e.g., local development files).
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
